// NODE_ENV constants.
export const DEVELOPMENT = 'development';
export const PRODUCTION = 'production';
export const TEST = 'test';

// Tokenable Type Constants
export const ADMIN_TOKENABLE_TYPE = 'Admin';
export const USER_TOKENABLE_TYPE = 'User';

// Repositories' constants
export const SEQUELIZE = 'SEQUELIZE';
export const PERMISSIONS_REPOSITORY = 'PERMISSIONS_REPOSITORY';
export const ADMINS_REPOSITORY = 'ADMINS_REPOSITORY';
export const ADMIN_PASSWORD_RESETS_REPOSITORY =
  'ADMIN_PASSWORD_RESETS_REPOSITORY';
export const APP_VERSION_LOGS_REPOSITORY = 'APP_VERSION_LOGS_REPOSITORY';
export const CITIES_REPOSITORY = 'CITIES_REPOSITORY';
export const CONTENT_PAGES_REPOSITORY = 'CONTENT_PAGES_REPOSITORY';
export const COUNTRIES_REPOSITORY = 'COUNTRIES_REPOSITORY';
export const MODEL_HAS_PERMISSIONS_REPOSITORY =
  'MODEL_HAS_PERMISSIONS_REPOSITORY';
export const MODEL_HAS_ROLES_REPOSITORY = 'MODEL_HAS_ROLES_REPOSITORY';
export const PASSWORD_RESETS_REPOSITORY = 'PASSWORD_RESETS_REPOSITORY';
export const PERSONAL_ACCESS_TOKENS_REPOSITORY =
  'PERSONAL_ACCESS_TOKENS_REPOSITORY';
export const ROLE_HAS_PERMISSIONS_REPOSITORY =
  'ROLE_HAS_PERMISSIONS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const SETTINGS_REPOSITORY = 'SETTINGS_REPOSITORY';
export const SOCIAL_LOGINS_REPOSITORY = 'SOCIAL_LOGINS_REPOSITORY';
export const STATES_REPOSITORY = 'STATES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';

// Wedding Group Booking Repositories
export const CURRENCIES_REPOSITORY = 'CURRENCIES_REPOSITORY';
export const HOTELS_REPOSITORY = 'HOTELS_REPOSITORY';
export const ROOM_TYPES_REPOSITORY = 'ROOM_TYPES_REPOSITORY';
export const WEDDING_GROUPS_REPOSITORY = 'WEDDING_GROUPS_REPOSITORY';
export const GROUP_ROOM_BLOCKS_REPOSITORY = 'GROUP_ROOM_BLOCKS_REPOSITORY';
export const GROUP_ADDONS_REPOSITORY = 'GROUP_ADDONS_REPOSITORY';
export const CANCELLATION_POLICIES_REPOSITORY = 'CANCELLATION_POLICIES_REPOSITORY';
export const GUESTS_REPOSITORY = 'GUESTS_REPOSITORY';
export const BOOKINGS_REPOSITORY = 'BOOKINGS_REPOSITORY';
export const BOOKING_ROOMS_REPOSITORY = 'BOOKING_ROOMS_REPOSITORY';
export const BOOKING_ADDONS_REPOSITORY = 'BOOKING_ADDONS_REPOSITORY';
export const BOOKING_HOLDS_REPOSITORY = 'BOOKING_HOLDS_REPOSITORY';
export const PAYMENTS_REPOSITORY = 'PAYMENTS_REPOSITORY';
export const INVOICES_REPOSITORY = 'INVOICES_REPOSITORY';
export const REFUNDS_REPOSITORY = 'REFUNDS_REPOSITORY';
export const NOTIFICATIONS_REPOSITORY = 'NOTIFICATIONS_REPOSITORY';
export const GROUP_ITINERARY_REPOSITORY = 'GROUP_ITINERARY_REPOSITORY';

// N8N Integration Repositories
export const WEBHOOKS_REPOSITORY = 'WEBHOOKS_REPOSITORY';
export const WEBHOOK_DELIVERY_LOGS_REPOSITORY = 'WEBHOOK_DELIVERY_LOGS_REPOSITORY';
export const API_KEYS_REPOSITORY = 'API_KEYS_REPOSITORY';

// Activity Logs Repository
export const ACTIVITY_LOGS_REPOSITORY = 'ACTIVITY_LOGS_REPOSITORY';

// Guest Flights Repository
export const GUEST_FLIGHTS_REPOSITORY = 'GUEST_FLIGHTS_REPOSITORY';

// Support Tickets Repository
export const SUPPORT_TICKETS_REPOSITORY = 'SUPPORT_TICKETS_REPOSITORY';
export const TICKET_MESSAGES_REPOSITORY = 'TICKET_MESSAGES_REPOSITORY';

// Namespaced repositories object for easier imports
export const REPOSITORIES = {
  GUEST_FLIGHTS_REPOSITORY: 'GUEST_FLIGHTS_REPOSITORY',
  BOOKINGS_REPOSITORY: 'BOOKINGS_REPOSITORY',
  BOOKING_HOLDS_REPOSITORY: 'BOOKING_HOLDS_REPOSITORY',
  GUESTS_REPOSITORY: 'GUESTS_REPOSITORY',
  WEDDING_GROUPS_REPOSITORY: 'WEDDING_GROUPS_REPOSITORY',
  HOTELS_REPOSITORY: 'HOTELS_REPOSITORY',
  ROOM_TYPES_REPOSITORY: 'ROOM_TYPES_REPOSITORY',
  GROUP_ROOM_BLOCKS_REPOSITORY: 'GROUP_ROOM_BLOCKS_REPOSITORY',
  GROUP_ADDONS_REPOSITORY: 'GROUP_ADDONS_REPOSITORY',
  PAYMENTS_REPOSITORY: 'PAYMENTS_REPOSITORY',
  INVOICES_REPOSITORY: 'INVOICES_REPOSITORY',
  REFUNDS_REPOSITORY: 'REFUNDS_REPOSITORY',
  CURRENCIES_REPOSITORY: 'CURRENCIES_REPOSITORY',
  GROUP_ITINERARY_REPOSITORY: 'GROUP_ITINERARY_REPOSITORY',
  ADMINS_REPOSITORY: 'ADMINS_REPOSITORY',
};
